name: CI

on:
  push:
    branches:
    - main
    - 251-support-env-vars-for-registry-auth-when-executing-kp-import
  pull_request: {}

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      uses: ./.github/actions/run-tests
    - name: Report coverage
      run: bash <(curl -s https://codecov.io/bash)
      env:
        CODECOV_TOKEN: b9667068-6fac-4787-8c05-d0b5d65f5adb